window.__KOL_DEFAULTS__ = {
  "kol": {
    "authors": [
      {"id":"karpathy","category":"前沿研究者","handle":"@karpathy","name":"Andrej Karpathy","field":"LLM 教育/agent 思辨","platform":"X","status":"keep","enabled":true},
      {"id":"ylecun","category":"前沿研究者","handle":"@ylecun","name":"Yann LeCun","field":"世界模型/深度学习","platform":"X","status":"keep","enabled":true},
      {"id":"demishassabis","category":"前沿研究者","handle":"@demishassabis","name":"Demis Hassabis","field":"DeepMind CEO","platform":"X","status":"keep","enabled":true},
      {"id":"ilyasut","category":"前沿研究者","handle":"@ilyasut","name":"Ilya Sutskever","field":"对齐(SSI)","platform":"X","status":"keep","enabled":true},
      {"id":"fchollet","category":"前沿研究者","handle":"@fchollet","name":"François Chollet","field":"ARC-AGI/Keras","platform":"X","status":"keep","enabled":true},
      {"id":"drfeifei","category":"前沿研究者","handle":"@drfeifei","name":"Fei-Fei Li","field":"空间智能(World Labs)","platform":"X","status":"keep","enabled":true},
      {"id":"openai","category":"大厂负责人与研究员","handle":"@OpenAI","name":"OpenAI","field":"OpenAI 官方研究/产品","platform":"X","status":"new","enabled":true},
      {"id":"sama","category":"大厂负责人与研究员","handle":"@sama","name":"Sam Altman","field":"OpenAI CEO","platform":"X","status":"keep","enabled":true},
      {"id":"gdb","category":"大厂负责人与研究员","handle":"@gdb","name":"Greg Brockman","field":"OpenAI 总裁","platform":"X","status":"keep","enabled":true},
      {"id":"merettm","category":"大厂负责人与研究员","handle":"@merettm","name":"Jakub Pachocki","field":"OpenAI 首席科学家","platform":"X","status":"keep","enabled":true},
      {"id":"darioamodei","category":"大厂负责人与研究员","handle":"@DarioAmodei","name":"Dario Amodei","field":"Anthropic CEO","platform":"X","status":"keep","enabled":true},
      {"id":"alexalbert__","category":"大厂负责人与研究员","handle":"@alexalbert__","name":"Alex Albert","field":"Anthropic DevRel","platform":"X","status":"new","enabled":true},
      {"id":"officiallogank","category":"大厂负责人与研究员","handle":"@OfficialLoganK","name":"Logan Kilpatrick","field":"Google AI Studio","platform":"X","status":"keep","enabled":true},
      {"id":"arthurmensch","category":"大厂负责人与研究员","handle":"@arthurmensch","name":"Arthur Mensch","field":"Mistral CEO","platform":"X","status":"keep","enabled":true},
      {"id":"miramurati","category":"大厂负责人与研究员","handle":"@miramurati","name":"Mira Murati","field":"Thinking Machines","platform":"X","status":"watch","enabled":true},
      {"id":"trq212","category":"AI工程与Agent","handle":"@trq212","name":"Thariq Shihipar","field":"Anthropic Claude Code/研究员长文","platform":"X","status":"new","enabled":true},
      {"id":"bcherny","category":"AI工程与Agent","handle":"@bcherny","name":"Boris Cherny","field":"Claude Code 作者/loop","platform":"X","status":"new","enabled":true},
      {"id":"swyx","category":"AI工程与Agent","handle":"@swyx","name":"Shawn Wang","field":"Latent Space/AI 工程","platform":"X","status":"keep","enabled":true},
      {"id":"simonw","category":"AI工程与Agent","handle":"@simonw","name":"Simon Willison","field":"agent 安全/prompt injection","platform":"X","status":"keep","enabled":true},
      {"id":"steipete","category":"AI工程与Agent","handle":"@steipete","name":"Peter Steinberger","field":"loop engineering 推手","platform":"X","status":"new","enabled":true},
      {"id":"addyosmani","category":"AI工程与Agent","handle":"@addyosmani","name":"Addy Osmani","field":"agentic engineering(Google)","platform":"X","status":"new","enabled":true},
      {"id":"mipsytipsy","category":"AI工程与Agent","handle":"@mipsytipsy","name":"Charity Majors","field":"可观测性/AI 工程","platform":"X","status":"new","enabled":true},
      {"id":"omarsar0","category":"AI工程与Agent","handle":"@omarsar0","name":"Elvis Saravia","field":"prompt(DAIR.AI)","platform":"X","status":"new","enabled":true},
      {"id":"natolambert","category":"开源与模型","handle":"@natolambert","name":"Nathan Lambert","field":"post-training(Ai2)","platform":"X","status":"keep","enabled":true},
      {"id":"jeremyphoward","category":"开源与模型","handle":"@jeremyphoward","name":"Jeremy Howard","field":"fast.ai/模型评测","platform":"X","status":"new","enabled":true},
      {"id":"teknium","category":"开源与模型","handle":"@Teknium","name":"Teknium","field":"Nous Research","platform":"X","status":"new","enabled":true},
      {"id":"zai_org","category":"开源与模型","handle":"@Zai_org","name":"Z.ai (智谱)","field":"GLM 开源模型","platform":"X","status":"new","enabled":true},
      {"id":"jietang","category":"开源与模型","handle":"@jietang","name":"唐杰","field":"Z.ai/智谱 创始人与 GLM","platform":"X","status":"new","enabled":true},
      {"id":"kimi_moonshot","category":"开源与模型","handle":"@Kimi_Moonshot","name":"Kimi.ai","field":"Moonshot/Kimi 官方模型更新","platform":"X","status":"new","enabled":true},
      {"id":"alibaba_qwen","category":"开源与模型","handle":"@Alibaba_Qwen","name":"Qwen","field":"通义千问官方模型/产品动作","platform":"X","status":"new","enabled":true},
      {"id":"metr_evals","category":"评测与安全","handle":"@METR_Evals","name":"METR","field":"危险能力评测","platform":"X","status":"new","enabled":true},
      {"id":"apolloaievals","category":"评测与安全","handle":"@apolloaievals","name":"Apollo Research","field":"对齐/欺骗评测","platform":"X","status":"new","enabled":true},
      {"id":"drjimfan","category":"具身与世界模型","handle":"@DrJimFan","name":"Jim Fan","field":"具身智能(NVIDIA)","platform":"X","status":"keep","enabled":true},
      {"id":"johnjumpersci","category":"具身与世界模型","handle":"@JohnJumperSci","name":"John Jumper","field":"AI for science(诺奖→Anthropic)","platform":"X","status":"new","enabled":true},
      {"id":"chelseabfinn","category":"具身与世界模型","handle":"@chelseabfinn","name":"Chelsea Finn","field":"机器人(Physical Intelligence)","platform":"X","status":"watch","enabled":true},
      {"id":"svlevine","category":"具身与世界模型","handle":"@svlevine","name":"Sergey Levine","field":"机器人 RL","platform":"X","status":"watch","enabled":true},
      {"id":"_akhaliq","category":"多模态与资讯速递","handle":"@_akhaliq","name":"AK","field":"论文/demo 第一传播","platform":"X","status":"keep","enabled":true},
      {"id":"rohanpaul_ai","category":"多模态与资讯速递","handle":"@rohanpaul_ai","name":"Rohan Paul","field":"AI 资讯/论文解读","platform":"X","status":"new","enabled":true},
      {"id":"kimmonismus","category":"多模态与资讯速递","handle":"@kimmonismus","name":"Chubby","field":"AI 突发快报","platform":"X","status":"new","enabled":true},
      {"id":"mreflow","category":"多模态与资讯速递","handle":"@mreflow","name":"Matt Wolfe","field":"AI 工具科普","platform":"X","status":"new","enabled":true},
      {"id":"sharbel","category":"多模态与资讯速递","handle":"@sharbel","name":"Sharbel","field":"GitHub 增速榜/开源情报","platform":"X","status":"new","enabled":true},
      {"id":"seelffff","category":"多模态与资讯速递","handle":"@seelffff","name":"self.dll","field":"开源 repo 速递","platform":"X","status":"new","enabled":true},
      {"id":"unslothai","category":"多模态与资讯速递","handle":"@UnslothAI","name":"Unsloth AI","field":"开源模型部署/实测","platform":"X","status":"new","enabled":true},
      {"id":"arena","category":"多模态与资讯速递","handle":"@arena","name":"Arena.ai","field":"模型与 Agent 独立评测","platform":"X","status":"new","enabled":true},
      {"id":"artificialanlys","category":"多模态与资讯速递","handle":"@ArtificialAnlys","name":"Artificial Analysis","field":"模型性能/成本独立评测","platform":"X","status":"new","enabled":true},
      {"id":"emollick","category":"应用与投资创业","handle":"@emollick","name":"Ethan Mollick","field":"AI 与职场(Wharton)","platform":"X","status":"keep","enabled":true},
      {"id":"andrewyng","category":"应用与投资创业","handle":"@AndrewYNg","name":"Andrew Ng","field":"AI 教育/趋势","platform":"X","status":"keep","enabled":true},
      {"id":"levie","category":"应用与投资创业","handle":"@levie","name":"Aaron Levie","field":"企业 AI/组织工作流(Box)","platform":"X","status":"new","enabled":true},
      {"id":"satyanadella","category":"应用与投资创业","handle":"@satyanadella","name":"Satya Nadella","field":"企业 AI/组织与平台(Microsoft)","platform":"X","status":"new","enabled":true},
      {"id":"bindureddy","category":"应用与投资创业","handle":"@bindureddy","name":"Bindu Reddy","field":"企业 AI agent(Abacus)","platform":"X","status":"new","enabled":true},
      {"id":"a16z","category":"应用与投资创业","handle":"@a16z","name":"a16z","field":"AI 投资","platform":"X","status":"new","enabled":true},
      {"id":"martin_casado","category":"应用与投资创业","handle":"@martin_casado","name":"Martin Casado","field":"AI 投资/政策(a16z)","platform":"X","status":"new","enabled":true},
      {"id":"0xcodez","category":"AI编码与loop圈","handle":"@0xCodez","name":"Codez","field":"loop engineering 解读","platform":"X","status":"new","enabled":true},
      {"id":"sairahul1","category":"AI编码与loop圈","handle":"@sairahul1","name":"Rahul","field":"loop/agent 工程","platform":"X","status":"new","enabled":true},
      {"id":"aravsrinivas","category":"AI编码与loop圈","handle":"@AravSrinivas","name":"Aravind Srinivas","field":"Perplexity CEO","platform":"X","status":"keep","enabled":true},
      {"id":"hamelhusain","category":"AI编码与loop圈","handle":"@HamelHusain","name":"Hamel Husain","field":"Evals/Agent 工程/业界方法论","platform":"X","status":"new","enabled":true},
      {"id":"svpino","category":"AI编码与loop圈","handle":"@svpino","name":"Santiago Valdarrama","field":"ML/Agent 工程趋势观点","platform":"X","status":"watch","enabled":true},
      {"id":"shawmakesmagic","category":"AIxCrypto与DeFAI","handle":"@shawmakesmagic","name":"Shaw Walters","field":"Eliza 框架","platform":"X","status":"keep","enabled":true},
      {"id":"aixbt_agent","category":"AIxCrypto与DeFAI","handle":"@aixbt_agent","name":"aixbt","field":"AI×crypto 情报 agent","platform":"X","status":"watch","enabled":true},
      {"id":"kylesamani","category":"AIxCrypto与DeFAI","handle":"@KyleSamani","name":"Kyle Samani","field":"Multicoin/理性质疑","platform":"X","status":"watch","enabled":true},
      {"id":"bengoertzel","category":"AIxCrypto与DeFAI","handle":"@bengoertzel","name":"Ben Goertzel","field":"去中心化 AI/AGI","platform":"X","status":"watch","enabled":true},
      {"id":"op7418","category":"国内中文圈","handle":"@op7418","name":"歸藏 (guizang.ai)","field":"AI 视觉/资讯(AIGC Weekly)","platform":"X","status":"new","enabled":true},
      {"id":"dotey","category":"国内中文圈","handle":"@dotey","name":"宝玉 (Baoyu)","field":"AI 工程/翻译","platform":"X","status":"new","enabled":true},
      {"id":"_zheergen","category":"国内中文圈","handle":"@_zheergen","name":"爱吃折耳根的Ace","field":"AI+股票投研(UZI-Skill)","platform":"X","status":"new","enabled":true},
      {"id":"xiaohu","category":"国内中文圈","handle":"@xiaohu","name":"Xiaohu","field":"国产模型/技术差距评估","platform":"X","status":"new","enabled":true},
      {"id":"wangyinrec","category":"国内中文圈","handle":"@wangyinrec","name":"Wangyin","field":"AI 产品规则/用户体验长文","platform":"X","status":"watch","enabled":true},
      {"id":"weibo-guizang","category":"国内中文圈","handle":"微博·歸藏的AI工具箱","name":"歸藏","field":"AI 工具","platform":"微博","status":"new","enabled":true},
      {"id":"weibo-baoyuxp","category":"国内中文圈","handle":"微博·宝玉xp","name":"宝玉","field":"AI 工程","platform":"微博","status":"new","enabled":true},
      {"id":"jike-orange-ai","category":"国内中文圈","handle":"即刻·orange.ai","name":"Orange","field":"AI 创业/内容","platform":"即刻","status":"watch","enabled":true}
    ]
  }
};
